# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "myf0VxPymHVcXxzMfoRQ2wfw1SgizDjQ9A97CdCGXQtBohiC+s35/glQnyyQZG9HwN8w8gLOUckaFy4KadRQA6ce+XJTtce629CgD77Vwg2MYeVp4cKvlPL8mdr6m1gkRrVe5i1cba+ljlJ//KkUmm5bB9rgh4abJWR34O49D2sLXHoJR/i8NWFNdhxd9U0/8gDZpWuoVeI8hypy6wwnh8SqVp7tDmONxKnS+N1+i0Kkpn3FvteHQtPC9enu6Bvivd6B5+IIo1IzrReZC0Dhu7Hus7x4ppov1VWDF3Ce7PohHX6M9/ZXUUo95yGaKG5xOqrcO2EJ1Zak8PI0UsEWdv+w57af+Je27vlRStoGvEVK0tqrv7qZVO5dLHANtJaNRZumNtGkESewm8WolE/in53onSG65kw8/rrCVpFBCyhVZX4C2v4DfC0bzI3vsQduHzsu/NbHhbgxC4IB4gUnXhD8Yab6d2BB9LPzNh6uQkIC62viMKa5B+q7HZdhqX9hYB0WRIdzFUaR6IXJlWzBBL0fyGahvkKsXMiai60oJK29cGMTobbBgdwmsmfwBow4MvRdVhcm0UAOcCIUjaj5QeBCfFHHT2i9+h2nJ6mT138wnZe7akcPx7Pq2BAZPNheSWxdyQo838LrhYU2LBauPZN54FnlGjcSPrSqfPTGVTo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
