travis:
  secure:
    BINSTAR_TOKEN: myf0VxPymHVcXxzMfoRQ2wfw1SgizDjQ9A97CdCGXQtBohiC+s35/glQnyyQZG9HwN8w8gLOUckaFy4KadRQA6ce+XJTtce629CgD77Vwg2MYeVp4cKvlPL8mdr6m1gkRrVe5i1cba+ljlJ//KkUmm5bB9rgh4abJWR34O49D2sLXHoJR/i8NWFNdhxd9U0/8gDZpWuoVeI8hypy6wwnh8SqVp7tDmONxKnS+N1+i0Kkpn3FvteHQtPC9enu6Bvivd6B5+IIo1IzrReZC0Dhu7Hus7x4ppov1VWDF3Ce7PohHX6M9/ZXUUo95yGaKG5xOqrcO2EJ1Zak8PI0UsEWdv+w57af+Je27vlRStoGvEVK0tqrv7qZVO5dLHANtJaNRZumNtGkESewm8WolE/in53onSG65kw8/rrCVpFBCyhVZX4C2v4DfC0bzI3vsQduHzsu/NbHhbgxC4IB4gUnXhD8Yab6d2BB9LPzNh6uQkIC62viMKa5B+q7HZdhqX9hYB0WRIdzFUaR6IXJlWzBBL0fyGahvkKsXMiai60oJK29cGMTobbBgdwmsmfwBow4MvRdVhcm0UAOcCIUjaj5QeBCfFHHT2i9+h2nJ6mT138wnZe7akcPx7Pq2BAZPNheSWxdyQo838LrhYU2LBauPZN54FnlGjcSPrSqfPTGVTo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
