travis:
  secure:
    BINSTAR_TOKEN: AbzNpbszQuhiav0VuyZNuQVHJjKlvoZlhHCX4TS+4NnfviGtwoOW4fknXVuLrXMKEzs0UHjkvpAcb8INmcaheNAA6U4bBvfgQ1J+EIhw7cbGu0ce/67zWg/UdCUcnBbBSw/SAk9QkjdYV29cfeeIG5pnAlArDV6CQuKJ5z23FTgiFutRZ63e/sPOWzGrxXx7rMQm0EIO2jIsVKHDjflG0B4LK/RsSH4LB8XOgvcPI2brF8XSIKgbSlsmxh6aJkyqxidNWA/mIWJycw18Rd4H2hu81grAxd+CUIgME6FfIYaWO6BHPowHKSfdcELNvmXnL+Q41X3h807tgxXSwR0Q9x/mojMWQgGuZWZDzWFe13u819YR2jSaijGSwCvrmy0OyHuVkNsy3BlvkxCBbqjW+w6bIDNXvxHxpvteI3hFIX54ebgulIsxWHqzKHLjLwPnvTESpW7FlPF4VGU4UbBe67w5Is/RMPN4M1aJ+aeWSoHvof6IkgtqteFJWzcRhL7S0j68yW+CkWOkP9KATDkDgz1jZlcmIHBs21whB9kj/7cLvx/gzWHyayUjBSZR4KyKGAp4zv2mV/EfTrD7DUVZKGUR+FM+FS4K+f09kE1Se91OPCJ4tU1nhBEgawI1/mjxKOG2BRhDk3NWUHT05M2sIUsw5ucphSsk90VKM19s7UE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
