travis:
  secure:
    BINSTAR_TOKEN: Y0t9RpYNSIo0YU7xF01LBTJlPYEo/p3utEwh9OZuNbU8r+SB3OqclmHCPY5FWoH7wvn8HXZEZ6FQIO7qS3QznSqS6omvHjNktdOxFDWlTFNKdVTkzbwrc6bzB6WQcdeOvCHzyjACNQF3fXtc+LMdosW/QqVsz38Q2QPawRWBt+WQrw0Dx6V/ROdchIsBHamgM6sPgvMzofYqEE6zh1Mvaa0JgTJMll1qhsDtZu+xMtqxciZ5ibIqLK5mnb06bpNgVN8iSqcXPYUrNv8HMDtvCpzZK3CCwlXMxPQv2te/bOrI0DarsqLw0ZNKgxaPdeO92ItWKsClPh5XMcvlqh7ACmjoE/Iwu198TmHrD68FTSMoHnYOK0fOX+ksrJwpZQLIMAauXA9tKy9G+zq7KFLW+GeloBq+KIBLOGOXWQ+Ob1cRRI4w0ayyPzATYlu01tC5rZrtfJMJkG1obj13BwtvzCUSZNiInaKcfiN16i+ri+lQ7NKQdf6x32YXdniNiQWM4mOOFS+vAsG/qmkVtcUXFqbdx+GpLJpFJzUr8DrPp8r48gU8j1WYfaIj+XbQBL4/3sKxsK2QeeFsXqPp6HCa1UnnQxxV46hNXMYcSROT4Kp2xaVA8qZzboV8kBMMgLwEQk0P+jKnjqxh6LidX+yWPeXa5kvIPrBzK4XZxK8gvuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
